name: Ungoogled-chromium tag automation
on: push

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: Create new tag
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Fetch tags
      run: |
        git fetch --tags
    - name: Install dependencies
      run: |
        sudo apt install jq -y
    - name: Bump version and push tag
      run: |
        ./devutils/create_new_tag.sh
