name: New version check

on:
  # enabling manual trigger
  workflow_dispatch:
  # running every 6 hours
  schedule:
    - cron: '48 */6 * * *'

jobs:
  check:
    # do not run in forks
    if: github.repository == 'ungoogled-software/ungoogled-chromium'
    runs-on: ubuntu-latest
    steps:
      - name: Set maintainer groups
        id: maintainers
        run: |
            echo "::set-output name=all::@networkException"
            echo "::set-output name=linux::@rany2"
            echo "::set-output name=windows::"
            echo "::set-output name=macos::"
      - name: Get the latest Chromium version
        id: latest-version
        run: |
          echo "linux_version=$( curl -s https://omahaproxy.appspot.com/linux )" >> $GITHUB_OUTPUT
          echo "win_version=$( curl -s https://omahaproxy.appspot.com/win )" >> $GITHUB_OUTPUT
          echo "mac_version=$( curl -s https://omahaproxy.appspot.com/mac )" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
      - name: Create Issue for all platforms
        if: |
          contains( steps.latest-version.outputs.win_version, steps.latest-version.outputs.mac_version ) &&
          contains( steps.latest-version.outputs.mac_version, steps.latest-version.outputs.linux_version )   
        uses: dblock/create-a-github-issue@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.latest-version.outputs.linux_version }}
          PLATFORM: all platforms
          NOTIFY_MAINTAINERS: "${{ steps.maintainers.outputs.all }} ${{ steps.maintainers.outputs.linux }} ${{ steps.maintainers.outputs.windows }} ${{ steps.maintainers.outputs.macos }}"
        with:
          update_existing: false
          search_existing: all
          filename:  .github/ISSUE_TEMPLATE/create-an--updating-to-chromium-x-x-x-x-.md
      - name: Create Issue for Linux
        if: |
          ! contains( steps.latest-version.outputs.win_version, steps.latest-version.outputs.mac_version ) ||
          ! contains( steps.latest-version.outputs.mac_version, steps.latest-version.outputs.linux_version )
        uses: dblock/create-a-github-issue@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.latest-version.outputs.linux_version }}
          PLATFORM: Linux
          NOTIFY_MAINTAINERS: "${{ steps.maintainers.outputs.all }} ${{ steps.maintainers.outputs.linux }}"
        with:
          update_existing: false
          search_existing: all
          filename:  .github/ISSUE_TEMPLATE/create-an--updating-to-chromium-x-x-x-x-.md
      - name: Create Issue for macOS
        if: |
          ! contains( steps.latest-version.outputs.win_version, steps.latest-version.outputs.mac_version ) ||
          ! contains( steps.latest-version.outputs.mac_version, steps.latest-version.outputs.linux_version )
        uses: dblock/create-a-github-issue@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.latest-version.outputs.mac_version }}
          PLATFORM: macOS
          NOTIFY_MAINTAINERS: "${{ steps.maintainers.outputs.all }} ${{ steps.maintainers.outputs.macos }}"
        with:
          update_existing: false
          search_existing: all
          filename:  .github/ISSUE_TEMPLATE/create-an--updating-to-chromium-x-x-x-x-.md
      - name: Create Issue for Windows
        if: |
          ! contains( steps.latest-version.outputs.win_version, steps.latest-version.outputs.mac_version ) ||
          ! contains( steps.latest-version.outputs.mac_version, steps.latest-version.outputs.linux_version )
        uses: dblock/create-a-github-issue@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.latest-version.outputs.win_version }}
          PLATFORM: Windows
          NOTIFY_MAINTAINERS: "${{ steps.maintainers.outputs.all }} ${{ steps.maintainers.outputs.windows }}"
        with:
          update_existing: false
          search_existing: all
          filename:  .github/ISSUE_TEMPLATE/create-an--updating-to-chromium-x-x-x-x-.md
