name: New version check

on:
  # enabling manual trigger
  workflow_dispatch:
  # running every 6 hours
  schedule:
    - cron: '48 */6 * * *'
  
jobs:
  check:
    # do not run in forks
    if: github.repository == 'ungoogled-software/ungoogled-chromium'
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest Chromium version
        id: latest-version
        run: |
          echo "::set-output name=linux_version::$( curl -s https://omahaproxy.appspot.com/linux )"
          echo "::set-output name=win_version::$( curl -s https://omahaproxy.appspot.com/win )"
          echo "::set-output name=mac_version::$( curl -s https://omahaproxy.appspot.com/mac )"
      - uses: actions/checkout@v2
      - name: Create Issue for all platforms
        if: |
          contains( steps.latest-version.outputs.win_version, steps.latest-version.outputs.mac_version ) &&
          contains( steps.latest-version.outputs.mac_version, steps.latest-version.outputs.linux_version )   
        uses: dblock/create-a-github-issue@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.latest-version.outputs.linux_version }}
          PLATFORM: all platforms
        with:
          update_existing: false
          search_existing: all
          filename:  .github/ISSUE_TEMPLATE/create-an--updating-to-chromium-x-x-x-x-.md
      - name: Create Issue for Linux
        if: |
          ! contains( steps.latest-version.outputs.win_version, steps.latest-version.outputs.mac_version ) ||
          ! contains( steps.latest-version.outputs.mac_version, steps.latest-version.outputs.linux_version )    
        uses: dblock/create-a-github-issue@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.latest-version.outputs.linux_version }}
          PLATFORM: Linux
        with:
          update_existing: false
          search_existing: all
          filename:  .github/ISSUE_TEMPLATE/create-an--updating-to-chromium-x-x-x-x-.md
      - name: Create Issue for macOS
        if: |
          ! contains( steps.latest-version.outputs.win_version, steps.latest-version.outputs.mac_version ) ||
          ! contains( steps.latest-version.outputs.mac_version, steps.latest-version.outputs.linux_version )     	    
        uses: dblock/create-a-github-issue@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.latest-version.outputs.mac_version }}
          PLATFORM: macOS
        with:
          update_existing: false
          search_existing: all
          filename:  .github/ISSUE_TEMPLATE/create-an--updating-to-chromium-x-x-x-x-.md
      - name: Create Issue for Windows
        if: |
          ! contains( steps.latest-version.outputs.win_version, steps.latest-version.outputs.mac_version ) ||
          ! contains( steps.latest-version.outputs.mac_version, steps.latest-version.outputs.linux_version )  
        uses: dblock/create-a-github-issue@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.latest-version.outputs.win_version }}
          PLATFORM: Windows
        with:
          update_existing: false
          search_existing: all
          filename:  .github/ISSUE_TEMPLATE/create-an--updating-to-chromium-x-x-x-x-.md
